### PR TITLE
Added createLink endpoint + tests

### PR DESCRIPTION
**Pull request by brownrw8**
This method is used to link an account(createAccount) to a party (either individual or entity) or to another account.

Per documentation: https://api-sandboxdash.norcapsecurities.com/admin_v3/documentation?mid=MTQ2

### CODE REVIEW

**Comment by shadowlion** [comment]
It looks good! Just one more thing:

I decided to use pnpm instead, so if you can change the following accordingly, I'll most likely approve it:

1. Pull the latest changes to include the pnpm lock file
2. Bump package.json by 1 (0.0.20 -> 0.0.21)

Thanks!

**Comment by brownrw8** [comment]
Merged upstream and bumped version (0.0.20 -> 0.0.21)

**Comment by shadowlion** [comment]
Check the linting of your `enums` file - I don't think it's using the `prettier` ruleset specified

**Comment by brownrw8** [comment]
Ah I see what I did wrong there - try it now

**Comment by shadowlion** [comment]
lgtm - thanks for contributing!

**Pull request merged**
